### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by nallion** [HenryDelMal/Berrygram_server#2]
When loading chat content, i get error:

`
root@test:~/Berrygram_server# python3.7 app.py
[2022-01-20 13:34:17 +0000] [21038] [INFO] Running on http://0.0.0.0:5000 (CTRL + C to quit)
CHECK AUTH:
nUMTGnkK9fjXiP0IENzZEw
True
THIS GUY IS AUTHORIZED!
GET CHAT LIST:
nUMTGnkK9fjXiP0IENzZEw
GET MESSAGE LIST:
nUMTGnkK9fjXiP0IENzZEw
[2022-01-20 13:34:33,493] ERROR in app: Exception on request POST /get_msgs
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/quart/app.py", line 1489, in handle_request
    return await self.full_dispatch_request(request_context)
  File "/usr/local/lib/python3.7/dist-packages/quart/app.py", line 1514, in full_dispatch_request
    result = await self.handle_user_exception(error)
  File "/usr/local/lib/python3.7/dist-packages/quart/app.py", line 964, in handle_user_exception
    raise error
  File "/usr/local/lib/python3.7/dist-packages/quart/app.py", line 1512, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/usr/local/lib/python3.7/dist-packages/quart/app.py", line 1557, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)
  File "app.py", line 122, in get_msgs
    return json.dumps(message_list)
  File "/usr/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PeerUser is not JSON serializable
`

try python 3.6, 3.7, 3.8, 3.9 with no luck( 
how fix this?

**Comment by gayatrisingh31** [comment]
Hi @nallion can i solve this error ?
